/**
 * Standard Sino-Vietnamese (Hán Việt), Onyomi, Kunyomi, Meaning, JLPT, Lookalikes reference table.
 * Verified against EDRDG KANJIDIC2 and Thiều Chửu / Trần Văn Chánh Sino-Vietnamese dictionary.
 * All text normalized to Unicode NFC.
 */

export interface KanjiSeedEntry {
  char: string;
  hanViet: string[];
  onyomi: string[];
  kunyomi: string[];
  meaningVi: string;
  jlpt?: 'N5' | 'N4' | 'N3' | 'N2' | 'N1';
  strokeCount?: number;
  lookalikes?: string[];
  radicals?: string[];
}

export const KANJI_DATA_MAP: Record<string, KanjiSeedEntry> = {
  // Common N5 / N4 Kanji
  '一': { char: '一', hanViet: ['NHẤT'], onyomi: ['イチ', 'イツ'], kunyomi: ['ひと', 'ひと.つ'], meaningVi: 'một, số một', jlpt: 'N5', strokeCount: 1, lookalikes: ['二', '十'] },
  '二': { char: '二', hanViet: ['NHỊ'], onyomi: ['ニ', 'ジ'], kunyomi: ['ふた', 'ふた.つ'], meaningVi: 'hai, số hai', jlpt: 'N5', strokeCount: 2, lookalikes: ['一', '三'] },
  '三': { char: '三', hanViet: ['TAM'], onyomi: ['サン'], kunyomi: ['み', 'み.つ', 'みっ.つ'], meaningVi: 'ba, số ba', jlpt: 'N5', strokeCount: 3, lookalikes: ['二'] },
  '四': { char: '四', hanViet: ['TỨ'], onyomi: ['シ'], kunyomi: ['よ', 'よ.つ', 'よっ.つ', 'よん'], meaningVi: 'bốn, số bốn', jlpt: 'N5', strokeCount: 5, lookalikes: ['西', '匹'] },
  '五': { char: '五', hanViet: ['NGŨ'], onyomi: ['ゴ'], kunyomi: ['いつ', 'いつ.つ'], meaningVi: 'năm, số năm', jlpt: 'N5', strokeCount: 4, lookalikes: ['互'] },
  '六': { char: '六', hanViet: ['LỤC'], onyomi: ['ロク'], kunyomi: ['む', 'む.つ', 'むっ.つ', 'むい'], meaningVi: 'sáu, số sáu', jlpt: 'N5', strokeCount: 4, lookalikes: ['穴', '立'] },
  '七': { char: '七', hanViet: ['THẤT'], onyomi: ['シチ'], kunyomi: ['なな', 'なな.つ', 'なの'], meaningVi: 'bảy, số bảy', jlpt: 'N5', strokeCount: 2, lookalikes: ['匕', '九'] },
  '八': { char: '八', hanViet: ['BÁT'], onyomi: ['ハチ'], kunyomi: ['や', 'や.つ', 'やっ.つ', 'よう'], meaningVi: 'tám, số tám', jlpt: 'N5', strokeCount: 2, lookalikes: ['人', '入'] },
  '九': { char: '九', hanViet: ['CỬU'], onyomi: ['キュウ', 'ク'], kunyomi: ['ここの', 'ここの.つ'], meaningVi: 'chín, số chín', jlpt: 'N5', strokeCount: 2, lookalikes: ['力', '丸'] },
  '十': { char: '十', hanViet: ['THẬP'], onyomi: ['ジュウ', 'ジッ'], kunyomi: ['とお', 'と'], meaningVi: 'mười, số mười', jlpt: 'N5', strokeCount: 2, lookalikes: ['千', '土'] },
  '百': { char: '百', hanViet: ['BÁCH'], onyomi: ['ヒャク'], kunyomi: ['もも'], meaningVi: 'trăm, số một trăm', jlpt: 'N5', strokeCount: 6, lookalikes: ['白'] },
  '千': { char: '千', hanViet: ['THIÊN'], onyomi: ['セン'], kunyomi: ['ち'], meaningVi: 'nghìn, số một nghìn', jlpt: 'N5', strokeCount: 3, lookalikes: ['十', '干'] },
  '万': { char: '万', hanViet: ['VẠN'], onyomi: ['マン', 'バン'], kunyomi: ['よろず'], meaningVi: 'vạn, mười nghìn', jlpt: 'N5', strokeCount: 3, lookalikes: ['方'] },
  '円': { char: '円', hanViet: ['VIÊN'], onyomi: ['エン'], kunyomi: ['まる.い'], meaningVi: 'đồng yên Nhật, hình tròn', jlpt: 'N5', strokeCount: 4 },
  '日': { char: '日', hanViet: ['NHẬT'], onyomi: ['ニチ', 'ジツ'], kunyomi: ['ひ', '-び', '-か'], meaningVi: 'ngày, mặt trời, Nhật Bản', jlpt: 'N5', strokeCount: 4, lookalikes: ['目', '白'] },
  '月': { char: '月', hanViet: ['NGUYỆT'], onyomi: ['ゲツ', 'ガツ'], kunyomi: ['つき'], meaningVi: 'mặt trăng, tháng', jlpt: 'N5', strokeCount: 4, lookalikes: ['日', '用'] },
  '火': { char: '火', hanViet: ['HỎA'], onyomi: ['カ'], kunyomi: ['ひ', '-び', 'ほ-'], meaningVi: 'lửa, thứ ba', jlpt: 'N5', strokeCount: 4, lookalikes: ['水'] },
  '水': { char: '水', hanViet: ['THỦY'], onyomi: ['スイ'], kunyomi: ['みず', 'みず-'], meaningVi: 'nước, thứ tư', jlpt: 'N5', strokeCount: 4, lookalikes: ['氷', '永'] },
  '木': { char: '木', hanViet: ['MỘC'], onyomi: ['ボク', 'モク'], kunyomi: ['き', 'こ-'], meaningVi: 'cây, gỗ, thứ năm', jlpt: 'N5', strokeCount: 4, lookalikes: ['本', '禾'] },
  '金': { char: '金', hanViet: ['KIM'], onyomi: ['キン', 'コン'], kunyomi: ['かね', 'かな-'], meaningVi: 'vàng, tiền, thứ sáu', jlpt: 'N5', strokeCount: 8, lookalikes: ['全'] },
  '土': { char: '土', hanViet: ['THỔ'], onyomi: ['ド', 'ト'], kunyomi: ['つち'], meaningVi: 'đất, thứ bảy', jlpt: 'N5', strokeCount: 3, lookalikes: ['士', '十'] },
  '年': { char: '年', hanViet: ['NIÊN'], onyomi: ['ネン'], kunyomi: ['とし'], meaningVi: 'năm, tuổi', jlpt: 'N5', strokeCount: 6 },
  '人': { char: '人', hanViet: ['NHÂN'], onyomi: ['ジン', 'ニン'], kunyomi: ['ひと', '-り', '-と'], meaningVi: 'người', jlpt: 'N5', strokeCount: 2, lookalikes: ['入', '八'] },
  '大': { char: '大', hanViet: ['ĐẠI'], onyomi: ['ダイ', 'タイ'], kunyomi: ['おお-', 'おお.きい', 'おお.いに'], meaningVi: 'lớn, to', jlpt: 'N5', strokeCount: 3, lookalikes: ['犬', '太'] },
  '小': { char: '小', hanViet: ['TIỂU'], onyomi: ['ショウ'], kunyomi: ['ちい.さい', 'こ-', 'お-'], meaningVi: 'nhỏ, bé', jlpt: 'N5', strokeCount: 3, lookalikes: ['少'] },
  '中': { char: '中', hanViet: ['TRUNG'], onyomi: ['チュウ'], kunyomi: ['なか', 'うち', 'あた.る'], meaningVi: 'ở giữa, bên trong', jlpt: 'N5', strokeCount: 4, lookalikes: ['申'] },
  '上': { char: '上', hanViet: ['THƯỢNG'], onyomi: ['ジョウ', 'ショウ'], kunyomi: ['うえ', 'あ.がる', 'のぼ.る'], meaningVi: 'trên, bề trên', jlpt: 'N5', strokeCount: 3, lookalikes: ['下', '止'] },
  '下': { char: '下', hanViet: ['HẠ'], onyomi: ['カ', 'ゲ'], kunyomi: ['した', 'さ.がる', 'くだ.る'], meaningVi: 'dưới, phía dưới', jlpt: 'N5', strokeCount: 3, lookalikes: ['上', '不'] },
  '前': { char: '前', hanViet: ['TIỀN'], onyomi: ['ゼン'], kunyomi: ['まえ'], meaningVi: 'trước', jlpt: 'N5', strokeCount: 9 },
  '後': { char: '後', hanViet: ['HẬU'], onyomi: ['ゴ', 'コウ'], kunyomi: ['のち', 'うし.ろ', 'あと', 'おく.れる'], meaningVi: 'sau, đằng sau', jlpt: 'N5', strokeCount: 9 },
  '学': { char: '学', hanViet: ['HỌC'], onyomi: ['ガク'], kunyomi: ['まな.ぶ'], meaningVi: 'học, trường học', jlpt: 'N5', strokeCount: 8, lookalikes: ['字'] },
  '校': { char: '校', hanViet: ['HIỆU'], onyomi: ['コウ'], kunyomi: [], meaningVi: 'trường học', jlpt: 'N5', strokeCount: 10 },
  '先': { char: '先', hanViet: ['TIÊN'], onyomi: ['セン'], kunyomi: ['さき', 'ま.ず'], meaningVi: 'trước, đi đầu', jlpt: 'N5', strokeCount: 6, lookalikes: ['失'] },
  '生': { char: '生', hanViet: ['SINH'], onyomi: ['セイ', 'ショウ'], kunyomi: ['い.きる', 'う.まれる', 'なま'], meaningVi: 'sống, sinh ra, tươi', jlpt: 'N5', strokeCount: 5, lookalikes: ['主'] },
  '時': { char: '時', hanViet: ['THỜI'], onyomi: ['ジ'], kunyomi: ['とき', '-どき'], meaningVi: 'thời gian, giờ', jlpt: 'N5', strokeCount: 10, lookalikes: ['待', '持'] },
  '分': { char: '分', hanViet: ['PHÂN', 'PHẬN'], onyomi: ['ブン', 'フン', 'ブ'], kunyomi: ['わ.ける', 'わ.かる'], meaningVi: 'phần, phút, hiểu', jlpt: 'N5', strokeCount: 4 },
  '今': { char: '今', hanViet: ['KIM'], onyomi: ['コン', 'キン'], kunyomi: ['いま'], meaningVi: 'bây giờ, nay', jlpt: 'N5', strokeCount: 4, lookalikes: ['令'] },
  '間': { char: '間', hanViet: ['GIAN'], onyomi: ['カン', 'ケン'], kunyomi: ['あいだ', 'ま', 'あい'], meaningVi: 'khoảng thời gian, khoảng giữa', jlpt: 'N5', strokeCount: 12, lookalikes: ['問', '聞'] },
  '本': { char: '本', hanViet: ['BẢN'], onyomi: ['ホン'], kunyomi: ['もと'], meaningVi: 'sách, gốc, bản', jlpt: 'N5', strokeCount: 5, lookalikes: ['木', '体'] },
  '語': { char: '語', hanViet: ['NGỮ'], onyomi: ['ゴ'], kunyomi: ['かた.る', 'かた.らう'], meaningVi: 'ngôn ngữ, kể chuyện', jlpt: 'N5', strokeCount: 14, lookalikes: ['話'] },
  '何': { char: '何', hanViet: ['HÀ'], onyomi: ['カ'], kunyomi: ['なに', 'なん'], meaningVi: 'cái gì, mấy', jlpt: 'N5', strokeCount: 7, lookalikes: ['向', '伺'] },
  '男': { char: '男', hanViet: ['NAM'], onyomi: ['ダン', 'ナン'], kunyomi: ['おとこ', 'お'], meaningVi: 'nam giới, đàn ông', jlpt: 'N5', strokeCount: 7, lookalikes: ['勇'] },
  '女': { char: '女', hanViet: ['NỮ'], onyomi: ['ジョ', 'ニョ'], kunyomi: ['おんな', 'め'], meaningVi: 'nữ giới, phụ nữ', jlpt: 'N5', strokeCount: 3, lookalikes: ['好'] },
  '子': { char: '子', hanViet: ['TỬ'], onyomi: ['シ', 'ス'], kunyomi: ['こ', '-こ'], meaningVi: 'con, đứa trẻ', jlpt: 'N5', strokeCount: 3, lookalikes: ['了'] },
  '友': { char: '友', hanViet: ['HỮU'], onyomi: ['ユウ'], kunyomi: ['とも'], meaningVi: 'bạn bè', jlpt: 'N5', strokeCount: 4, lookalikes: ['反', '支'] },
  '父': { char: '父', hanViet: ['PHỤ'], onyomi: ['フ'], kunyomi: ['ちち'], meaningVi: 'cha, bố', jlpt: 'N5', strokeCount: 4, lookalikes: ['文'] },
  '母': { char: '母', hanViet: ['MẪU'], onyomi: ['ボ'], kunyomi: ['はは'], meaningVi: 'mẹ', jlpt: 'N5', strokeCount: 5, lookalikes: ['毎'] },
  '車': { char: '車', hanViet: ['XA'], onyomi: ['シャ'], kunyomi: ['くるま'], meaningVi: 'xe cộ, ô tô', jlpt: 'N5', strokeCount: 7, lookalikes: ['東'] },
  '行': { char: '行', hanViet: ['HÀNH', 'HÀNG'], onyomi: ['コウ', 'ギョウ', 'アン'], kunyomi: ['い.く', 'ゆ.く', 'おこな.う'], meaningVi: 'đi, tiến hành, hàng', jlpt: 'N5', strokeCount: 6 },
  '来': { char: '来', hanViet: ['LAI'], onyomi: ['ライ', 'タイ'], kunyomi: ['く.る', 'きた.る', 'き.たる'], meaningVi: 'đến, tới', jlpt: 'N5', strokeCount: 7, lookalikes: ['未', '米'] },
  '食': { char: '食', hanViet: ['THỰC'], onyomi: ['ショク', 'ジキ'], kunyomi: ['た.べる', 'く.う'], meaningVi: 'ăn, món ăn', jlpt: 'N5', strokeCount: 9, lookalikes: ['飲'] },
  '飲': { char: '飲', hanViet: ['ẨM'], onyomi: ['イン'], kunyomi: ['の.む'], meaningVi: 'uống', jlpt: 'N5', strokeCount: 12, lookalikes: ['食'] },
  '見': { char: '見', hanViet: ['KIẾN'], onyomi: ['ケン'], kunyomi: ['み.る', 'み.える', 'み.せる'], meaningVi: 'nhìn, xem, thấy', jlpt: 'N5', strokeCount: 7, lookalikes: ['目', '貝'] },
  '聞': { char: '聞', hanViet: ['VĂN', 'VẤN'], onyomi: ['ブン', 'モン'], kunyomi: ['き.く', 'き.こえる'], meaningVi: 'nghe, hỏi', jlpt: 'N5', strokeCount: 14, lookalikes: ['問', '間'] },
  '言': { char: '言', hanViet: ['NGÔN'], onyomi: ['ゲン', 'ゴン'], kunyomi: ['い.う', 'こと'], meaningVi: 'nói, lời nói', jlpt: 'N5', strokeCount: 7, lookalikes: ['話'] },
  '話': { char: '話', hanViet: ['THOẠI'], onyomi: ['ワ'], kunyomi: ['はな.す', 'はなし'], meaningVi: 'nói chuyện, cuộc trò chuyện', jlpt: 'N5', strokeCount: 13, lookalikes: ['語'] },
  '読': { char: '読', hanViet: ['ĐỘC'], onyomi: ['ドク', 'トク'], kunyomi: ['よ.む'], meaningVi: 'đọc', jlpt: 'N5', strokeCount: 14 },
  '書': { char: '書', hanViet: ['THƯ'], onyomi: ['ショ'], kunyomi: ['か.く'], meaningVi: 'viết, sách', jlpt: 'N5', strokeCount: 10, lookalikes: ['昼'] },
  '買': { char: '買', hanViet: ['MÃI'], onyomi: ['バイ'], kunyomi: ['か.う'], meaningVi: 'mua', jlpt: 'N5', strokeCount: 12, lookalikes: ['売'] },
  '入': { char: '入', hanViet: ['NHẬP'], onyomi: ['ニュウ'], kunyomi: ['はい.る', 'い.る', 'い.れる'], meaningVi: 'vào, cho vào', jlpt: 'N5', strokeCount: 2, lookalikes: ['人', '八'] },
  '出': { char: '出', hanViet: ['XUẤT'], onyomi: ['シュツ', 'スイ'], kunyomi: ['で.る', 'だ.す'], meaningVi: 'ra ngoài, đưa ra', jlpt: 'N5', strokeCount: 5, lookalikes: ['山'] },
  '高': { char: '高', hanViet: ['CAO'], onyomi: ['コウ'], kunyomi: ['たか.い', 'たか'], meaningVi: 'cao, đắt', jlpt: 'N5', strokeCount: 10, lookalikes: ['京'] },
  '安': { char: '安', hanViet: ['AN'], onyomi: ['アン'], kunyomi: ['やす.い'], meaningVi: 'rẻ, yên tâm, an toàn', jlpt: 'N5', strokeCount: 6, lookalikes: ['字'] },
  '新': { char: '新', hanViet: ['TÂN'], onyomi: ['シン'], kunyomi: ['あたら.しい', 'あら.た'], meaningVi: 'mới', jlpt: 'N5', strokeCount: 13, lookalikes: ['親'] },
  '古': { char: '古', hanViet: ['CỔ'], onyomi: ['コ'], kunyomi: ['ふる.い'], meaningVi: 'cũ', jlpt: 'N5', strokeCount: 5, lookalikes: ['舌'] },
  '多': { char: '多', hanViet: ['ĐA'], onyomi: ['タ'], kunyomi: ['おお.い'], meaningVi: 'nhiều', jlpt: 'N5', strokeCount: 6, lookalikes: ['夕'] },
  '少': { char: '少', hanViet: ['THIỂU', 'THIẾU'], onyomi: ['ショウ'], kunyomi: ['すく.ない', 'すこ.し'], meaningVi: 'ít, một chút', jlpt: 'N5', strokeCount: 4, lookalikes: ['小'] },
  '手': { char: '手', hanViet: ['THỦ'], onyomi: ['シュ'], kunyomi: ['て', 'て-'], meaningVi: 'tay, bàn tay', jlpt: 'N5', strokeCount: 4, lookalikes: ['毛'] },
  '目': { char: '目', hanViet: ['MỤC'], onyomi: ['モク', 'ボク'], kunyomi: ['め', '-め'], meaningVi: 'mắt, mục lục', jlpt: 'N5', strokeCount: 5, lookalikes: ['日', '自'] },
  '耳': { char: '耳', hanViet: ['NHĨ'], onyomi: ['ジ'], kunyomi: ['みみ'], meaningVi: 'tai, thính giác', jlpt: 'N5', strokeCount: 6 },
  '口': { char: '口', hanViet: ['KHẨU'], onyomi: ['コウ', 'ク'], kunyomi: ['くち'], meaningVi: 'miệng, cửa', jlpt: 'N5', strokeCount: 3, lookalikes: ['日', '品'] },
  '足': { char: '足', hanViet: ['TÚC'], onyomi: ['ソク'], kunyomi: ['あし', 'た.りる', 'た.す'], meaningVi: 'chân, đầy đủ', jlpt: 'N5', strokeCount: 7 },
  '会': { char: '会', hanViet: ['HỘI'], onyomi: ['カイ', 'エ'], kunyomi: ['あ.う'], meaningVi: 'gặp gỡ, hội họp', jlpt: 'N5', strokeCount: 6, lookalikes: ['合'] },
  '社': { char: '社', hanViet: ['XÃ'], onyomi: ['シャ'], kunyomi: ['やしろ'], meaningVi: 'công ty, đền thần', jlpt: 'N5', strokeCount: 7 },
  '店': { char: '店', hanViet: ['ĐIẾM'], onyomi: ['テン'], kunyomi: ['みせ', 'たな'], meaningVi: 'cửa tiệm, cửa hàng', jlpt: 'N5', strokeCount: 8 },
  '駅': { char: '駅', hanViet: ['DỊCH'], onyomi: ['エキ'], kunyomi: [], meaningVi: 'nhà ga', jlpt: 'N5', strokeCount: 14 },
  '道': { char: '道', hanViet: ['ĐẠO'], onyomi: ['ドウ', 'トウ'], kunyomi: ['みち'], meaningVi: 'con đường, đạo', jlpt: 'N5', strokeCount: 12 },
  '電': { char: '電', hanViet: ['ĐIỆN'], onyomi: ['デン'], kunyomi: [], meaningVi: 'điện', jlpt: 'N5', strokeCount: 13, lookalikes: ['雷'] },
  '気': { char: '気', hanViet: ['KHÍ'], onyomi: ['キ', 'ケ'], kunyomi: ['いき'], meaningVi: 'khí, tinh thần, tâm trạng', jlpt: 'N5', strokeCount: 6, lookalikes: ['汽'] },
  '天': { char: '天', hanViet: ['THIÊN'], onyomi: ['テン'], kunyomi: ['あまつ', 'あめ', 'あま'], meaningVi: 'trời, bầu trời', jlpt: 'N5', strokeCount: 4, lookalikes: ['夫', '矢'] },
  '雨': { char: '雨', hanViet: ['VŨ'], onyomi: ['ウ'], kunyomi: ['あめ', 'あま-'], meaningVi: 'mưa', jlpt: 'N5', strokeCount: 8, lookalikes: ['両'] },
  '白': { char: '白', hanViet: ['BẠCH'], onyomi: ['ハク', 'ビャク'], kunyomi: ['しろ', 'しろ.い'], meaningVi: 'màu trắng', jlpt: 'N5', strokeCount: 5, lookalikes: ['百', '日'] },
  '黒': { char: '黒', hanViet: ['HẮC'], onyomi: ['コク'], kunyomi: ['くろ', 'くろ.い'], meaningVi: 'màu đen', jlpt: 'N5', strokeCount: 11, lookalikes: ['里'] },
  '赤': { char: '赤', hanViet: ['XÍCH'], onyomi: ['セキ', 'シャク'], kunyomi: ['あか', 'あか.い'], meaningVi: 'màu đỏ', jlpt: 'N5', strokeCount: 7 },
  '青': { char: '青', hanViet: ['THANH'], onyomi: ['セイ', 'ショウ'], kunyomi: ['あお', 'あお.い'], meaningVi: 'màu xanh lam', jlpt: 'N5', strokeCount: 8 },

  // Kanji frequent in N3 Mimikara
  '性': { char: '性', hanViet: ['TÍNH'], onyomi: ['セイ', 'ショウ'], kunyomi: ['さが'], meaningVi: 'tính chất, giới tính', jlpt: 'N3', strokeCount: 8, lookalikes: ['快', '情'] },
  '齢': { char: '齢', hanViet: ['LINH'], onyomi: ['レイ'], kunyomi: ['よわい', 'とし'], meaningVi: 'tuổi tác', jlpt: 'N3', strokeCount: 17, lookalikes: ['歯'] },
  '司': { char: '司', hanViet: ['TY', 'TƯ'], onyomi: ['シ'], kunyomi: ['つかさど.る'], meaningVi: 'cai quản, quản lý', jlpt: 'N3', strokeCount: 5, lookalikes: ['同', '句'] },
  '相': { char: '相', hanViet: ['TƯƠNG', 'TƯỚNG'], onyomi: ['ソウ', 'ショウ'], kunyomi: ['あい-'], meaningVi: 'lẫn nhau, bộ mặt, tướng', jlpt: 'N3', strokeCount: 9, lookalikes: ['想', '木'] },
  '対': { char: '対', hanViet: ['ĐỐI'], onyomi: ['タイ', 'ツイ'], kunyomi: ['あいて', 'こた.える'], meaningVi: 'đối ứng, đối diện', jlpt: 'N3', strokeCount: 7, lookalikes: ['村'] },
  '合': { char: '合', hanViet: ['HỢP'], onyomi: ['ゴウ', 'ガッ', 'カッ'], kunyomi: ['あ.う', 'あ.わす', 'あ.わせる'], meaningVi: 'hợp, đúng, cùng nhau', jlpt: 'N3', strokeCount: 6, lookalikes: ['会', '台'] },
  '知': { char: '知', hanViet: ['TRI'], onyomi: ['チ'], kunyomi: ['し.る', 'し.らせる'], meaningVi: 'biết, thông tri', jlpt: 'N4', strokeCount: 8, lookalikes: ['和'] },
  '仲': { char: '仲', hanViet: ['TRỌNG'], onyomi: ['チュウ'], kunyomi: ['なか'], meaningVi: 'mối quan hệ, thân thiết', jlpt: 'N3', strokeCount: 6, lookalikes: ['中', '件'] },
  '誕': { char: '誕', hanViet: ['ĐẢN'], onyomi: ['タン'], kunyomi: [], meaningVi: 'sinh ra, giáng sinh', jlpt: 'N3', strokeCount: 15 },
  '身': { char: '身', hanViet: ['THÂN'], onyomi: ['シン'], kunyomi: ['み'], meaningVi: 'thân thể, bản thân', jlpt: 'N3', strokeCount: 7 },
  '故': { char: '故', hanViet: ['CỐ'], onyomi: ['コ'], kunyomi: ['ゆえ'], meaningVi: 'cũ, nguyên nhân, quá cố', jlpt: 'N3', strokeCount: 9, lookalikes: ['政'] },
  '郷': { char: '郷', hanViet: ['HƯƠNG'], onyomi: ['キョウ', 'ゴウ'], kunyomi: ['さと'], meaningVi: 'quê hương, làng', jlpt: 'N3', strokeCount: 11 },
  '成': { char: '成', hanViet: ['THÀNH'], onyomi: ['セイ', 'ジョウ'], kunyomi: ['な.る', 'な.す'], meaningVi: 'thành công, trở thành', jlpt: 'N3', strokeCount: 6, lookalikes: ['城'] },
  '長': { char: '長', hanViet: ['TRƯỜNG', 'TRƯỞNG'], onyomi: ['チョウ'], kunyomi: ['なが.い', 'おさ'], meaningVi: 'dài, người đứng đầu', jlpt: 'N5', strokeCount: 8 },
  '進': { char: '進', hanViet: ['TIẾN'], onyomi: ['シン'], kunyomi: ['すす.む', 'すす.める'], meaningVi: 'tiến bộ, tiến lên', jlpt: 'N3', strokeCount: 11, lookalikes: ['近', '道'] },
  '退': { char: '退', hanViet: ['THOÁI'], onyomi: ['タイ'], kunyomi: ['しりぞ.く', 'ひ.く'], meaningVi: 'lui lại, rút lui, nghỉ việc', jlpt: 'N3', strokeCount: 9, lookalikes: ['追'] },
  '職': { char: '職', hanViet: ['CHỨC'], onyomi: ['ショク'], kunyomi: [], meaningVi: 'nghề nghiệp, chức vụ', jlpt: 'N3', strokeCount: 18, lookalikes: ['識'] },
  '失': { char: '失', hanViet: ['THẤT'], onyomi: ['シツ'], kunyomi: ['うしな.う'], meaningVi: 'mất mát, thất bại', jlpt: 'N3', strokeCount: 5, lookalikes: ['矢', '先'] },
  '業': { char: '業', hanViet: ['NGHIỆP'], onyomi: ['ギョウ', 'ゴウ'], kunyomi: ['わざ'], meaningVi: 'sự nghiệp, nghề nghiệp', jlpt: 'N3', strokeCount: 13 },
  '残': { char: '残', hanViet: ['TÀN'], onyomi: ['ザン'], kunyomi: ['のこ.る', 'のこ.す'], meaningVi: 'còn lại, tàn tích', jlpt: 'N3', strokeCount: 10, lookalikes: ['桟'] },
  '活': { char: '活', hanViet: ['HOẠT'], onyomi: ['カツ'], kunyomi: ['い.きる'], meaningVi: 'hoạt bát, sinh hoạt', jlpt: 'N3', strokeCount: 9, lookalikes: ['話'] },
  '通': { char: '通', hanViet: ['THÔNG'], onyomi: ['ツウ', 'ツ'], kunyomi: ['とお.る', 'かよ.う'], meaningVi: 'đi lại, thông qua', jlpt: 'N4', strokeCount: 10, lookalikes: ['道'] },
  '勤': { char: '勤', hanViet: ['CẦN'], onyomi: ['キン', 'ゴン'], kunyomi: ['つと.める', 'つと.まる'], meaningVi: 'làm việc, cần mẫn', jlpt: 'N3', strokeCount: 12 },
  '歴': { char: '歴', hanViet: ['LỊCH'], onyomi: ['レキ'], kunyomi: [], meaningVi: 'lịch sử, trải qua', jlpt: 'N3', strokeCount: 14 },
  '給': { char: '給', hanViet: ['CẤP'], onyomi: ['キュウ'], kunyomi: ['たま.う'], meaningVi: 'tiền lương, cung cấp', jlpt: 'N3', strokeCount: 12, lookalikes: ['結'] },
  '料': { char: '料', hanViet: ['LIỆU'], onyomi: ['リョウ'], kunyomi: [], meaningVi: 'nguyên liệu, tiền phí', jlpt: 'N4', strokeCount: 10, lookalikes: ['科'] },
  '預': { char: '預', hanViet: ['DỰ'], onyomi: ['ヨ'], kunyomi: ['あず.かる', 'あず.ける'], meaningVi: 'gửi, giữ đồ, chăm sóc', jlpt: 'N3', strokeCount: 13, lookalikes: ['頂', '領'] },
  '荷': { char: '荷', hanViet: ['HÀ'], onyomi: ['カ'], kunyomi: ['に'], meaningVi: 'hành lý, vác', jlpt: 'N3', strokeCount: 10, lookalikes: ['何'] },
  '物': { char: '物', hanViet: ['VẬT'], onyomi: ['ブツ', 'モツ'], kunyomi: ['もの'], meaningVi: 'đồ vật, sự vật', jlpt: 'N4', strokeCount: 8, lookalikes: ['特'] },
  '面': { char: '面', hanViet: ['DIỆN'], onyomi: ['メン', 'ベン'], kunyomi: ['おも', 'おもて', 'つら'], meaningVi: 'mặt, phương diện', jlpt: 'N3', strokeCount: 9 },
  '接': { char: '接', hanViet: ['TIẾP'], onyomi: ['セツ', 'ショウ'], kunyomi: ['つ.ぐ'], meaningVi: 'tiếp xúc, nối liền', jlpt: 'N3', strokeCount: 11 },
  '重': { char: '重', hanViet: ['TRỌNG', 'TRÙNG'], onyomi: ['ジュウ', 'チョウ'], kunyomi: ['おも.い', 'かさ.なる'], meaningVi: 'nặng, quan trọng, chồng chất', jlpt: 'N4', strokeCount: 9 },
  '要': { char: '要', hanViet: ['YẾU', 'YÊU'], onyomi: ['ヨウ'], kunyomi: ['い.る', 'かなめ'], meaningVi: 'quan trọng, cần thiết', jlpt: 'N3', strokeCount: 9, lookalikes: ['西', '安'] },
  '試': { char: '試', hanViet: ['THÍ'], onyomi: ['シ'], kunyomi: ['こころ.みる', 'ため.す'], meaningVi: 'thử nghiệm, kỳ thi', jlpt: 'N4', strokeCount: 13, lookalikes: ['話'] },
  '験': { char: '験', hanViet: ['NGHIỆM'], onyomi: ['ケン', 'ゲン'], kunyomi: ['ため.す'], meaningVi: 'thí nghiệm, trải nghiệm', jlpt: 'N4', strokeCount: 18, lookalikes: ['険'] },
  '格': { char: '格', hanViet: ['CÁCH'], onyomi: ['カク', 'コウ'], kunyomi: [], meaningVi: 'tư cách, quy cách', jlpt: 'N3', strokeCount: 10, lookalikes: ['村'] }
};
